# Generated by Django 4.2.3 on 2023-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
