# Generated by Django 4.2.3 on 2023-08-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_publisher_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='country',
        ),
    ]
