# Generated by Django 4.2.3 on 2023-09-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_remove_publisher_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
